language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

services: mongodb

before_script:
  - sudo pecl install mongodb
  - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script: ./composer test